version: 2
updates:
  - package-ecosystem: "maven"
    open-pull-requests-limit: 3
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 3
    directory: "/"
    schedule:
      interval: "daily"
